### ISSUE TITLE
NPM package publishing?

### ISSUE THREAD

**Issue by blakeblackshear** [mister-ben/videojs-seek-buttons#124]
I noticed that the version on npmjs.org is still 3.0.1. Are there plans to continue pushing this to npm?

**Comment by mister-ben** [comment]
4.0.2 is available on npm as `next` ot `latest8`. The idea was to tag that as `latest`, but since there's a standard option for skip buttons in Video.js as of 8.2.0, versions of this plugin compatible with v8 are now redundant.

https://videojs.com/guides/options/#skipbuttons

**Comment by blakeblackshear** [comment]
Thanks
