### ISSUE TITLE
The seek button is not displaying correctly in version 8.1 and above

### ISSUE THREAD

**Issue by akosphp** [mister-ben/videojs-seek-buttons#130]
In v8.0.4:
![image](https://user-images.githubusercontent.com/13352440/235728083-9a8d2fa6-706b-4ee1-a0d9-e98e42616521.png)

In v.8.1.1, v8.2.1, v8.3.0:
![image](https://user-images.githubusercontent.com/13352440/235727703-4c0ea8c1-d409-4926-b2b9-15ffde69c7b9.png)

**Comment by akosphp** [comment]
Browser: Chrome 112.0

**Comment by mister-ben** [comment]
Fixed in 4.0.3. Thanks for reporting.

However you might want to use the standard skip button option in Video.js 8.2.0 +

**Comment by akosphp** [comment]
Thank you for the quick fix and the tip as well!
