### ISSUE TITLE
Seek buttons do not show up 

### ISSUE THREAD

**Issue by ThatGalNatalie** [mister-ben/videojs-seek-buttons#15]
![Screen Shot 2019-04-05 at 8 11 01 PM](https://user-images.githubusercontent.com/40726391/55663007-fc5fbe00-57de-11e9-8dec-c7922b12770d.png)

![Screen Shot 2019-04-05 at 8 08 49 PM](https://user-images.githubusercontent.com/40726391/55663021-27e2a880-57df-11e9-8ceb-232787a6cfdc.png)

Any ideas on why this is happening?

**Comment by mister-ben** [comment]
You probably don't have the CSS. I've just realised the boilerplate readme does not mention the CSS, sorry.

**Comment by ThatGalNatalie** [comment]
Do you know where I can get the CSS to make it visible?

**Comment by mister-ben** [comment]
There'll be a videojs-seek-buttons.css at the same path as you're loading the js from.

**Comment by mister-ben** [comment]
updated readme to mention css

**Comment by Kunal-04** [comment]
I have the same issue please help me.

I use HTML to do this task, also install the plugin of seek-button but buttons are not shown.
![Capture](https://user-images.githubusercontent.com/87192112/125089682-315cc880-e0ec-11eb-81f0-30f952154cfd.PNG)

**Comment by therealabdi2** [comment]
@Kunal-04 were you able to solve this
its not working for me either
added the css path as well

**Comment by yahyarahman1309-prog** [comment]
D
