### ISSUE TITLE
 "The element or ID supplied is not valid" ..  Can anyone help me please?

### ISSUE THREAD

**Issue by os9sur** [mister-ben/videojs-seek-buttons#173]
videojs-seek-buttons.min.js:2 Uncaught TypeError: Class constructor s cannot be invoked without 'new'
    at new r (videojs-seek-buttons.min.js:2:1017)
    at Ir.addChild (video.min.js:12:23143)
    at videojs-seek-buttons.min.js:2:689
    at b.<anonymous> (videojs-seek-buttons.min.js:2:892)
    at b.<anonymous> (video.min.js:12:24999)
    at Array.forEach (<anonymous>)
    at b.<anonymous> (video.min.js:12:24977)
    at video.min.js:12:27660

![2024-06-21_145349](https://github.com/mister-ben/videojs-seek-buttons/assets/6024166/07b6b228-d11d-4b86-8a0c-a1592c311cab)

**Comment by mister-ben** [comment]
It sounds like you are using v3.x of the lluging with video.js 8, which are incompatible. You can use v4.x, `videojs-seek-buttons@next`, however there are native skip buttons in video.js 8 that you can use instead.

https://videojs.com/guides/options/#skipbuttons

**Comment by mister-ben** [comment]
It looks like you've not included Video.js's CSS. See an example here
https://github.com/videojs/video.js/blob/main/sandbox/skip-buttons.html.example
