### ISSUE TITLE
The "Inclusion" section of the README.md needs some work

### ISSUE THREAD

**Issue by OwenEdwards** [mister-ben/videojs-seek-buttons#2]
> ```
> <script src="path/to/video.js/dist/video.js"></script>
> <script src="path/to/videojs-playlist/dist/videojs-seek-buttons.js"></script>
> ```

I think this should be `path/to/videojs-seek-buttons/dist/videojs-seek-buttons.js`, and the user also needs to include `dist/videojs-seek-buttons.css`.

-Captain Pedantic, at your service!

**Comment by mister-ben** [comment]
Thanks! Will fix that.
