### ISSUE TITLE
Change order in control bar

### ISSUE THREAD

**Issue by StigoSvK** [mister-ben/videojs-seek-buttons#26]
Hi, thanks for this easy to use plugin. I just wondering if there is possibility to change position of seek buttons in control bar. I found this condition in your plugin:
`    player.controlBar.el().insertBefore(
      player.controlBar.seekForward.el(),
      player.controlBar.el().firstChild.nextSibling
    );`

So I'm guessing it is not possible?

Thanks

**Comment by mister-ben** [comment]
The position is hardcoded but that should be easy to add support. There's been a better way to position child elements for a long time that for whatever reason I hadn't updated here yet.
