### ISSUE TITLE
Seek Button Skips Ahead

### ISSUE THREAD

**Issue by rgoodridge** [mister-ben/videojs-seek-buttons#39]
I currently have my config set to skip 1 frame at a time

**player.seekButtons({
          forward: 0.1,
          back: 0.1
        });**

But sometimes it will decide to skip 2 frames, it occurs on both forwards and backwards, i have no idea how to troubleshoot this as i receive no errors in the console.

**Comment by mister-ben** [comment]
Some additional discussion on frame accurate seeking here https://video-dev.slack.com/archives/C7NGPHMUJ/p1620830301034600
