### ISSUE TITLE
Seek Forward not showing in Safari Mobile

### ISSUE THREAD

**Issue by hunterjm** [mister-ben/videojs-seek-buttons#46]
I for the life of me can not figure this out. It does not happen with the back button, and the CSS looks identical. The Seek forward button shows briefly as the control bar fades in or out, but when the control bar is fully active it is not visible. Everything functions as expected on desktop, and it does not appear to be a viewport issue because removing the back button from the UI has the same result. The functionality still works fine if the place where the button should be is touched.

![IMG_E4297](https://user-images.githubusercontent.com/747670/120852912-e1b53b00-c548-11eb-88a1-64a4d6bc9056.JPG)

**Comment by mister-ben** [comment]
Safari is weird with `rotateY`. I can reproduce that only inconsistently, but using a `scale` transform instead seems to be fine.
