### ISSUE TITLE
Override click handler?

### ISSUE THREAD

**Issue by dijonkitchen** [mister-ben/videojs-seek-buttons#48]
Is it possible to override the on click handler for each of the seek buttons? Looking to seek forward/back and do some other side effect.

**Comment by mister-ben** [comment]
You can add a listener on the buttons like any other Video.js component to add an additional action.

    player.controlBar.seekForward.on('click', e => { /* ...*/ });

To override the handler, you could create a new component that extends the `SeekButton` component, in the same way `SeekButton` extends `Button` in https://github.com/mister-ben/videojs-seek-buttons/blob/9b4599ee7aa3692283139887f111ddc5c924d1df/src/plugin.js#L86-L140

**Comment by dijonkitchen** [comment]
Thanks!

I didn't update my post, but ended up doing this: 

```ts
        const SeekButton = videojs.getComponent('SeekButton');
        SeekButton.prototype.handleClick = (event) => {
            seekClickHandler(event, ...);
        };
```
