### ISSUE TITLE
How to use language files in javascript

### ISSUE THREAD

**Issue by tobpe** [mister-ben/videojs-seek-buttons#66]
How can I use language files? For example, if I want to create one for Swedish.

Do you have a simple example with javascript?

**Comment by mister-ben** [comment]
The JSON files are for use with Video.js's standard [`addLanguage` API](https://docs.videojs.com/tutorial-languages.html).

    video.js.addLanguage('sv', translationsjson); 

For the translations in the repo (PRs welcome!) a js file is added to the dist folder that can be used directly in a script tag.

    <script src="https://unpkg.com/browse/videojs-seek-buttons@2.2.0/dist/lang/de.js"></script>
